version: '3.8'

services:
  app:

    build:
      context: .
      dockerfile: docker/homologation/Dockerfile
    container_name: content-hub
    ports:
      - "8010:80"  # Mapeie a porta do host para a porta do Apache dentro do contêiner
    volumes:
      #- ./server:/var/www/server  # Mapeie o diretório do seu projeto Laravel para o contêiner
      - ./server/storage:/var/www/server/storage
      - ./server/.env:/var/www/server/.env
      - ./server/bootstrap:/var/www/server/bootstraps