FROM php:8.2-fpm

ENV PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig \
    CURL_CFLAGS=-I/usr/include \
    CURL_LIBS=-L/usr/lib/x86_64-linux-gnu-lcurl \
    LIBXML_CFLAGS=-I/path/to/libxml2/include \
    LIBXML_LIBS=-L/path/to/libxml2/lib-lxml2 


# Install environment dependencies
RUN apt-get update \
	# gd
	&& apt-get install -y build-essential \
         openssl \
         nginx \
         libfreetype6-dev \
         libjpeg-dev \
         libpng-dev \
         libwebp-dev \
         zlib1g-dev \
         libzip-dev \
         gcc \
         g++ \
         make \
         nano \
         unzip \
         curl \
         git \
         jpegoptim \
         optipng \
         pngquant \
         gifsicle \
         locales \
         libonig-dev  \
         libpq-dev \
        libcurl4-openssl-dev \
        libxml2-dev \
        figlet \
    && docker-php-ext-configure gd  \
	&& docker-php-ext-install gd \
	# gmp
	&& apt-get install -y --no-install-recommends libgmp-dev libxml2-dev \
	&& docker-php-ext-install gmp \
	# pgsql
	&& docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
        && docker-php-ext-install pdo pdo_pgsql pgsql mbstring \
        && docker-php-ext-install curl \
	# opcache
	&& docker-php-ext-enable opcache \
	# exif
    && docker-php-ext-install exif \
    && docker-php-ext-install sockets \
    && docker-php-ext-install pcntl \
    && docker-php-ext-install bcmath \
	# zip
	&& docker-php-ext-install zip \
	&& apt-get autoclean -y \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /tmp/pear/ && \
    echo 'figlet -t "Lapig Content Hub"' >> ~/.bashrc